import { useEffect, useState } from "react";
import { products as seedProducts } from "../data/products";
import type { Product } from "../data/products";
import AddButton from "../components/AddButton";
import { defaultMoods, type Mood } from "../data/moods";
interface HomeProps { onAddToCart: (product: Product) => void; onViewProduct: (product: Product) => void; onNavigate: (page: string) => void; catalogProducts?: Product[]; moods?: Mood[]; dailyDropProductId?: string; featuredTrioIds?: string[]; }

export default function Home({ onAddToCart, onViewProduct, onNavigate, catalogProducts, moods = defaultMoods, dailyDropProductId = "", featuredTrioIds = [] }: HomeProps) {
 const products = catalogProducts?.length ? catalogProducts : seedProducts;
 const [moodIndex, setMoodIndex] = useState(0);
 const [hitIndex, setHitIndex] = useState(0);
 useEffect(() => {
   const elements = document.querySelectorAll<HTMLElement>("[data-reveal]");
   const observer = new IntersectionObserver((entries) => {
     entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add("reveal-in"); observer.unobserve(entry.target); } });
   }, { threshold: 0.14, rootMargin: "0px 0px -45px" });
   elements.forEach((element) => observer.observe(element));
   return () => observer.disconnect();
 }, []);
 const hero=products.find(p=>p.id==="chanel-no5")??products[0];
 const publishedProducts = products.filter((product) => !(product as Product & { status?: string }).status || (product as Product & { status?: string }).status === "На витрине");
 const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86_400_000);
 const scentOfDay = publishedProducts.find((product) => product.id === dailyDropProductId) ?? publishedProducts[dayOfYear % Math.max(1, publishedProducts.length)] ?? hero;
 // Hit Parade — редакционная подборка, а не побочный результат импорта CSV.
 const weeklyHits = products.filter((product) => product.weeklyHit && (!(product as Product & { status?: string }).status || (product as Product & { status?: string }).status === "На витрине"));
 const hits = weeklyHits.slice(0,4);
 const hitProduct=hits[hitIndex]??hits[0]??null; const mood=moods[moodIndex]; const moodProduct=products.find((product)=>product.id===mood.productId)??products.find((product)=>product.family===mood.family)??products[moodIndex];
 return <div className="beauty-page pt-16"><div className="beauty-strip">БЕСПЛАТНАЯ ДОСТАВКА ОТ 15 000 ₽ <span>•</span> НОВЫЕ АРОМАТЫ КАЖДУЮ НЕДЕЛЮ <span>•</span> ПОДАРОК К ЗАКАЗУ</div>
 <section className="mx-auto max-w-[1440px] px-4 py-5 sm:px-6 sm:py-6 lg:px-9 lg:py-9" data-reveal><div className="scent-drop scent-drop-hero"><div className="scent-drop-rail"><div>{Array.from({ length: 4 }, (_, index) => <span key={index}>SCENT OF THE DAY <b>✦</b> ОДИН ФЛАКОН · ОДИН ДЕНЬ <b>✦</b></span>)}</div></div><div className="scent-drop-copy"><p>DAILY DROP / {String(dayOfYear).padStart(3, "0")}</p><h2>АРОМАТ<br /><em>СЕГОДНЯ.</em></h2><span>Сегодня этот флакон звучит громче остальных. Один аромат в фокусе — чтобы остановиться и почувствовать его по‑настоящему.</span><div><button onClick={() => onViewProduct(scentOfDay)}>Открыть аромат <i>↗</i></button><small>Новый выбор —<br />каждый день в 00:00 МСК</small></div></div><div className="scent-drop-object"><span>01 / 01</span><img src={scentOfDay.image} alt={`${scentOfDay.brand} ${scentOfDay.name}`} loading="lazy" decoding="async" /><div><p>{scentOfDay.brand}</p><strong>{scentOfDay.name}</strong><b>{scentOfDay.price.toLocaleString("ru-RU")} ₽</b></div></div></div></section>
 <section className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-9"><div className="mood-studio" data-reveal><div className="mood-studio-head"><div><p>MOOD STUDIO / 01</p><h2>ВКЛЮЧИ<br /><span>СОСТОЯНИЕ.</span></h2></div><p className="mood-studio-copy">Аромат — это не категория. Это переключатель, который можно носить на себе.</p></div><div className="mood-studio-stage"><div className="mood-radial" /><div className="mood-choice-list">{moods.map((item,index)=><button key={item.label} onClick={()=>setMoodIndex(index)} className={`mood-choice ${moodIndex===index?"is-active":""}`}><span className="mood-choice-num">0{index+1}</span><span className="mood-choice-name">{item.label}</span><span className="mood-choice-dot" /></button>)}</div><div key={mood.label} className={`mood-match-card mood-swap ${mood.color}`}><div className="mood-match-art"><img src={moodProduct.image} alt={`${moodProduct.brand} ${moodProduct.name}`} loading="lazy" decoding="async" /></div><div className="mood-match-content"><p>ПОДХОДЯЩИЙ СИГНАЛ</p><button onClick={()=>onViewProduct(moodProduct)}>{moodProduct.brand}<br /><strong>{moodProduct.name}</strong></button><span>{moodProduct.notes.top.slice(0,3).join(" · ")}</span></div><AddButton onAdd={() => onAddToCart(moodProduct)} label className="mood-match-add" /></div></div><div className="mood-studio-foot"><p>{mood.caption}</p><button onClick={()=>onNavigate("catalog")}>ОТКРЫТЬ ВСЕ СОСТОЯНИЯ <span>↗</span></button></div></div></section>

 <section className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-9" data-reveal><div className="hit-parade"><div className="hit-parade-head"><p>WEEKLY / HIT PARADE</p><span>01—04</span></div><div className="hit-parade-main">{hitProduct ? <><div key={hitProduct.id} className="hit-parade-image hit-swap"><span>№ 0{hitIndex + 1}</span><img src={hitProduct.image} alt={`${hitProduct.brand} ${hitProduct.name}`} loading="lazy" decoding="async" /></div><div key={`${hitProduct.id}-info`} className="hit-parade-feature hit-swap"><p>Самый желанный<br />аромат недели</p><button onClick={() => onViewProduct(hitProduct)}><span>{hitProduct.brand}</span>{hitProduct.name}</button><div className="hit-parade-meta"><span>{hitProduct.family}</span><span>{hitProduct.notes.top.slice(0, 2).join(" / ")}</span></div><div className="hit-parade-cta"><strong>{hitProduct.price.toLocaleString("ru-RU")} ₽</strong><AddButton onAdd={() => onAddToCart(hitProduct)} label /></div></div><div className="hit-parade-list">{hits.map((product,index)=><button key={product.id} onClick={() => setHitIndex(index)} className={hitIndex===index?"is-active":""}><span>0{index + 1}</span><i>{product.brand}</i><strong>{product.name}</strong><b>↗</b></button>)}<button className="hit-parade-all" onClick={() => onNavigate("catalog")}>Все хиты <span>→</span></button></div></> : <div className="hit-parade-empty"><p>WEEKLY EDIT / 00</p><b>НОВАЯ НЕДЕЛЯ.<br /><em>НОВЫЕ ФАВОРИТЫ.</em></b><span>Скоро здесь появится свежий выбор Makibo — четыре аромата, которые хочется носить прямо сейчас.</span><i aria-hidden="true">✦</i></div>}</div></div></section>
 <section className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-9" data-reveal><div className="makibo-pass"><div className="makibo-pass-card pass-float"><div className="makibo-pass-card-top"><span>MAKIBO PASS</span><span>MEMBER 001</span></div><div className="makibo-pass-card-main"><p>Красивые<br />привычки<br />окупаются.</p><span>✦</span></div><div className="makibo-pass-card-bottom"><span>BEAUTY / REWARDS</span><span>2026</span></div></div><div className="makibo-pass-copy"><p>Личный бонусный счёт</p><h2>БОЛЬШЕ<br />ТЕБЯ —<br /><span>БОЛЬШЕ ВЫГОД.</span></h2><div className="makibo-pass-perks"><span><b>01</b> Миниатюры к заказу</span><span><b>02</b> Ранний доступ к новинкам</span><span><b>03</b> Персональные предложения</span></div><a href="https://t.me/makibo_manager" target="_blank" rel="noreferrer">Получить Makibo Pass <i>↗</i></a></div></div></section>
 </div>;
}
