import { useState } from "react";
import type { Product } from "../data/products";
import { products } from "../data/products";
import AddButton from "../components/AddButton";

interface ProductPageProps { product: Product; onAddToCart: (product: Product) => void; onViewProduct: (product: Product) => void; onBack: () => void; }
const levels = ["Верхние ноты", "Сердце", "Шлейф"] as const;

export default function ProductPage({ product, onAddToCart, onViewProduct, onBack }: ProductPageProps) {
  const [volume, setVolume] = useState(product.volume[0]);
  const [noteLevel, setNoteLevel] = useState(0);
  const noteSets = [product.notes.top, product.notes.heart, product.notes.base];
  const hasNotes = noteSets.some((notes) => notes.length > 0);
  const related = products.filter((item) => item.id !== product.id && (item.family === product.family || item.brand === product.brand)).slice(0, 3);
  return <div className="beauty-page min-h-screen pt-[95px] lg:pt-[103px]"><div className="mx-auto max-w-[1440px] px-4 py-6 sm:px-6 lg:px-9 lg:py-9">
    <button onClick={onBack} className="product-back">← В каталог</button>
    <main className="product-new mt-5"><section className="product-stage"><div className="product-stage-meta"><span>АРОМАТ / {product.year ?? "—"}</span><span>{product.gender}</span></div><div className="product-stage-shape" /><img src={product.image} alt={`${product.brand} ${product.name}`} fetchPriority="high" decoding="async" /><div className="product-stage-stamp">MAKIBO<br />OBJECT<br />{String(product.year ?? 0).slice(-2)}</div><div className="product-stage-tags">{product.isNew && <span>NEW</span>}{product.isBestseller && <span>BEST SELLER</span>}</div></section>
      <section className="product-summary"><p className="product-eyebrow">{product.brand}</p><h1>{product.name}</h1><div className="product-summary-details"><span>{product.family}</span><span>·</span><span>{product.gender}</span><span>·</span><span>{product.year}</span></div><p className="product-description">{product.description}</p><div className="product-volume"><p>Выберите объём</p><div>{product.volume.map((item) => <button key={item} onClick={() => setVolume(item)} className={volume === item ? "is-active" : ""}>{item} мл</button>)}</div></div><div className="product-buy"><div><span>Цена</span><strong>{product.price.toLocaleString("ru-RU")} ₽</strong></div><AddButton onAdd={() => onAddToCart(product)} label className="product-add" /></div><div className="product-guarantees"><span>✓ Оригинальная продукция</span><span>✓ Доставка 1–3 дня</span></div></section>
    </main>
    <section className="notes-lab"><div className="notes-lab-title"><p>АРОМАТ В ДВИЖЕНИИ</p><h2>КАРТА<br /><span>НОТ.</span></h2><p>{hasNotes ? "Нажмите на слой и посмотрите, как раскрывается композиция." : "Мы уточняем официальную пирамиду у поставщика и не добавляем ноты наугад."}</p></div>{hasNotes ? <div className="notes-lab-map"><div className="notes-lab-tabs">{levels.map((level,index) => <button key={level} onClick={() => setNoteLevel(index)} className={noteLevel === index ? "is-active" : ""}><b>0{index + 1}</b>{level}<i>+</i></button>)}</div><div className={`notes-lab-notes level-${noteLevel}`}><p>{levels[noteLevel]}</p><div>{noteSets[noteLevel].map((note, index) => <span key={note} style={{ transitionDelay: `${index * 70}ms` }}>{note}</span>)}</div></div></div> : <div className="notes-lab-pending"><b>Карта нот<br />на уточнении.</b><span>Добавим только подтверждённые ноты.</span><i>✦</i></div>}</section>
    <section className="product-ritual"><header><p>MAKIBO / CARE ROUTE</p><h2>ЗАКАЗ<br /><em>БЕЗ СЮРПРИЗОВ.</em></h2><span>Ничего лишнего: покажем именно ваш флакон, соберём и отправим.</span></header><ol><li><div className="product-ritual-mark">✦</div><b>01 / УПАКУЕМ</b><strong>Фирменная<br />упаковка</strong><p>Упакуем аккуратно — можно дарить, даже если подарок себе.</p></li><li><div className="product-ritual-mark">↗</div><b>02 / ОТПРАВИМ</b><strong>Доставка<br />за наш счёт</strong><p>Бесплатно от 15 000 ₽ по Москве и России.</p></li><li><div className="product-ritual-mark">◉</div><b>03 / ПОКАЖЕМ</b><strong>Фото до<br />оплаты</strong><p>Покажем флакон в Telegram, затем пришлём ссылку на оплату.</p></li></ol></section>
    {related.length > 0 && <section className="product-related"><div className="flex items-end justify-between"><div><p>МОЖЕТ ПОНРАВИТЬСЯ</p><h2>ЕЩЁ В ЭТОМ<br />НАСТРОЕНИИ.</h2></div><button onClick={onBack}>Смотреть всё →</button></div><div className="mt-6 grid grid-cols-3 gap-3 sm:gap-5">{related.map((item) => <article key={item.id}><button onClick={() => onViewProduct(item)} className="block w-full overflow-hidden rounded-2xl bg-[#efefea]"><img src={item.image} alt={`${item.brand} ${item.name}`} loading="lazy" decoding="async" className="aspect-[.86] w-full object-cover mix-blend-multiply" /></button><p>{item.brand}</p><button onClick={() => onViewProduct(item)}>{item.name}</button></article>)}</div></section>}
  </div></div>;
}
